[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.25.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
