name: CI
on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
        with:
          path: src/github.com/${{ github.repository }}
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Set environment variables
        shell: bash
        run: |
          echo '::set-env name=GOPATH::${{ runner.workspace }}'
          echo '::add-path::${{ runner.workspace }}/bin'
      - name: Print env
        run: |
          go env
          env
      - name: Build
        run: go build -v -mod vendor
      - name: Test
        run: go test -v -mod vendor
