name: CI
on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v

      - name: Build Docker image
        run: docker build -t aws-s3-reverse-proxy .

      - name: Run Docker image
        run: docker run --rm aws-s3-reverse-proxy --help
